apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fm-chain-db-pvc
  namespace: fm-chain
  labels:
    app: fm-chain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
